# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-alpine

# Install MCP CLI runtime dependency
RUN pip install --no-cache-dir mcp[cli]>=1.6.0

# Set working directory
WORKDIR /app

# Copy server implementation
COPY server.py .

# Expose standard port environment variable (if needed)
# No HTTP exposure since this is a stdio server

# Default command to run the MCP server over stdio
CMD ["python", "server.py"]
